# Generated by Django 4.2.6 on 2023-10-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='specs',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
