# Generated by Django 3.2.22 on 2023-11-02 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='stripe_payment_intent_id',
            new_name='stripe_id',
        ),
    ]
