# Generated by Django 3.2.22 on 2023-11-03 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_stripe_payment_intent_id_invoice_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='count',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('requires_payment', 'Requires payment'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='requires_payment', max_length=32),
        ),
    ]
