# Generated by Django 3.2.22 on 2023-11-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='type',
            new_name='event_type',
        ),
        migrations.AddField(
            model_name='log',
            name='error_message',
            field=models.TextField(null=True),
        ),
    ]
